wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
num_epochs:
  desc: null
  value: 10
weight_decay:
  desc: null
  value: 0.02
batch_size:
  desc: null
  value: 32.0
micro_batch_size:
  desc: null
  value: 4
dataset:
  desc: null
  value: gigaspeech
devices:
  desc: null
  value: 1
max_input_length:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719355478
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.19
      5: 0.17.2
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
